Repository 9oormthon-univ/2024_DANPOONG_TEAM_2_BE, pull requests merged in 2024-11, with the labels that each got.

#3 global, swagger setting
  build.gradle
  src/main/java/com/moa/moabackend/global/config/JpaAuditingConfig.java
  src/main/java/com/moa/moabackend/global/config/SwaggerConfig.java
  src/main/java/com/moa/moabackend/global/entity/BaseEntity.java
  src/main/java/com/moa/moabackend/global/error/ControllerAdvice.java
  src/main/java/com/moa/moabackend/global/error/dto/ErrorResponse.java
  src/main/java/com/moa/moabackend/global/error/exception/AccessDeniedGroupException.java
  src/main/java/com/moa/moabackend/global/error/exception/AuthGroupException.java
  src/main/java/com/moa/moabackend/global/error/exception/CustomAuthenticationFailureHandler.java
  src/main/java/com/moa/moabackend/global/error/exception/InvalidGroupException.java
  src/main/java/com/moa/moabackend/global/error/exception/NotFoundGroupException.java
  src/main/java/com/moa/moabackend/global/template/RspTemplate.java
Labels: Setting

#4 카카오 소셜로그인 + JWT 구현
  src/main/java/com/moa/moabackend/auth/api/AuthController.java
  src/main/java/com/moa/moabackend/auth/api/AuthControllerDocs.java
  src/main/java/com/moa/moabackend/auth/api/dto/request/TokenReqDto.java
  src/main/java/com/moa/moabackend/auth/api/dto/response/MemberLoginResDto.java
  src/main/java/com/moa/moabackend/auth/api/dto/response/UserInfo.java
  src/main/java/com/moa/moabackend/auth/application/AuthMemberService.java
  src/main/java/com/moa/moabackend/auth/application/AuthService.java
  src/main/java/com/moa/moabackend/auth/application/AuthServiceFactory.java
  src/main/java/com/moa/moabackend/auth/application/TokenService.java
  src/main/java/com/moa/moabackend/global/config/SecurityConfig.java
  src/main/java/com/moa/moabackend/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/moa/moabackend/global/jwt/TokenProvider.java
  src/main/java/com/moa/moabackend/global/jwt/api/dto/TokenDto.java
  src/main/java/com/moa/moabackend/global/oauth/api/dto/response/KakaoTokenResponse.java
  src/main/java/com/moa/moabackend/global/oauth/application/KaKaoAuthService.java
  src/main/java/com/moa/moabackend/global/oauth/exception/OAuthException.java
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/member/domain/Role.java
  src/main/java/com/moa/moabackend/member/domain/SocialType.java
  src/main/java/com/moa/moabackend/member/domain/repository/MemberRepository.java
  src/main/java/com/moa/moabackend/member/exception/MemberNotFoundException.java
  src/main/resources/application.yml
Labels: Feature

#7 table setting
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/member/domain/Mileage.java
  src/main/java/com/moa/moabackend/member/domain/VoucherBarcode.java
  src/main/java/com/moa/moabackend/store/domain/Store.java
  src/main/java/com/moa/moabackend/store/domain/StoreImage.java
  src/main/java/com/moa/moabackend/store/domain/StoreLocation.java
  src/main/java/com/moa/moabackend/store/domain/StorePunding.java
  src/main/java/com/moa/moabackend/store/domain/StoreScrap.java
Labels: Feature, Setting

#9 Feat(#8): 회원 유형 수정 기능 구현
  src/main/java/com/moa/moabackend/member/api/MemberController.java
  src/main/java/com/moa/moabackend/member/api/MemberControllerDocs.java
  src/main/java/com/moa/moabackend/member/api/dto/request/MemberTypeUpdateReqDto.java
  src/main/java/com/moa/moabackend/member/application/MemberService.java
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/member/domain/MemberType.java
  src/main/java/com/moa/moabackend/member/exception/InvalidMemberTypeException.java
Labels: Feature

#12 Feat(#11): Add CRUD API
  src/main/java/com/moa/moabackend/store/api/StoreController.java
  src/main/java/com/moa/moabackend/store/api/StoreControllerDocs.java
  src/main/java/com/moa/moabackend/store/api/dto/request/LocationDto.java
  src/main/java/com/moa/moabackend/store/api/dto/request/SearchByLocationReqDto.java
  src/main/java/com/moa/moabackend/store/api/dto/request/StoreReqDto.java
  src/main/java/com/moa/moabackend/store/api/dto/response/AddressResDto.java
  src/main/java/com/moa/moabackend/store/api/dto/response/StoreResDto.java
  src/main/java/com/moa/moabackend/store/application/StoreService.java
  src/main/java/com/moa/moabackend/store/domain/Store.java
  src/main/java/com/moa/moabackend/store/domain/StoreImage.java
  src/main/java/com/moa/moabackend/store/domain/StoreLocation.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreImageRepository.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreLocationRepository.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreRepository.java
  src/main/java/com/moa/moabackend/store/exception/RevGeocodeNotFoundException.java
Labels: API, Feature

#16 Feat(#10): 내 펀딩 내역 조회 기능 구현
  src/main/java/com/moa/moabackend/member/api/MemberController.java
  src/main/java/com/moa/moabackend/member/api/MemberControllerDocs.java
  src/main/java/com/moa/moabackend/member/api/dto/response/CouponInfoResDto.java
  src/main/java/com/moa/moabackend/member/api/dto/response/MyPundingHistoryResDto.java
  src/main/java/com/moa/moabackend/member/application/MemberService.java
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/member/domain/repository/MileageRepository.java
  src/main/java/com/moa/moabackend/store/domain/StorePunding.java
  src/main/java/com/moa/moabackend/store/domain/repository/StorePundingRepository.java
Labels: Feature

#19 feat(store): Rework for new design
  src/main/java/com/moa/moabackend/member/application/MemberService.java
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/store/api/StoreController.java
  src/main/java/com/moa/moabackend/store/api/StoreControllerDocs.java
  src/main/java/com/moa/moabackend/store/api/dto/request/SearchByLocationReqDto.java
  src/main/java/com/moa/moabackend/store/api/dto/request/StoreReqDto.java
  src/main/java/com/moa/moabackend/store/api/dto/response/StoreResDto.java
  src/main/java/com/moa/moabackend/store/application/StoreService.java
  src/main/java/com/moa/moabackend/store/domain/CertifiedType.java
  src/main/java/com/moa/moabackend/store/domain/Store.java
  src/main/java/com/moa/moabackend/store/domain/StoreFunding.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreFundingRepository.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreLocationRepository.java
  src/main/java/com/moa/moabackend/store/domain/repository/StorePundingRepository.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreRepository.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreScrapRepository.java
Labels: API, Feature, Refactor

#21 Feat(#17): 마일리지, 상품권 기능 구현
  src/main/java/com/moa/moabackend/global/entity/Status.java
  src/main/java/com/moa/moabackend/member/application/MemberService.java
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/store/domain/Store.java
  src/main/java/com/moa/moabackend/store/domain/StoreFunding.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreFundingRepository.java
  src/main/java/com/moa/moabackend/store/exception/StoreFundingNotFoundException.java
  src/main/java/com/moa/moabackend/store/exception/StoreNotFoundException.java
  src/main/java/com/moa/moabackend/voucher/api/VoucherController.java
  src/main/java/com/moa/moabackend/voucher/api/VoucherControllerDocs.java
  src/main/java/com/moa/moabackend/voucher/api/request/ExchangeVoucherDirectlyReqDto.java
  src/main/java/com/moa/moabackend/voucher/api/request/ExchangeVoucherReqDto.java
  src/main/java/com/moa/moabackend/voucher/api/request/ReturnMileageReqDto.java
  src/main/java/com/moa/moabackend/voucher/application/VoucherService.java
  src/main/java/com/moa/moabackend/voucher/domain/Voucher.java
  src/main/java/com/moa/moabackend/voucher/domain/repository/VoucherRepository.java
  src/main/java/com/moa/moabackend/voucher/exception/VoucherNotFoundException.java
Labels: API, Feature

#26 Refactor(#10): 가장 선호하는 상점의 타입 반환 추가
  src/main/java/com/moa/moabackend/member/api/dto/response/MemberInfoResDto.java
  src/main/java/com/moa/moabackend/member/application/MemberService.java
Labels: Refactor

#30 Feat: 내 펀딩 리턴 확인 정보 조회 기능 구현
  src/main/java/com/moa/moabackend/funding/api/FundingController.java
  src/main/java/com/moa/moabackend/funding/api/FundingControllerDocs.java
  src/main/java/com/moa/moabackend/funding/api/response/MyFundingsReturnResDto.java
  src/main/java/com/moa/moabackend/funding/application/FundingService.java
  src/main/java/com/moa/moabackend/member/api/MemberControllerDocs.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreFundingRepository.java
  src/main/java/com/moa/moabackend/voucher/application/VoucherService.java
  src/main/java/com/moa/moabackend/voucher/exception/InsufficientMileageException.java
  src/main/java/com/moa/moabackend/voucher/exception/MileageAlreadyReturnException.java
Labels: Feature

#32 Feat(member): add setting favorited type
  src/main/java/com/moa/moabackend/member/api/MemberController.java
  src/main/java/com/moa/moabackend/member/api/MemberControllerDocs.java
  src/main/java/com/moa/moabackend/member/api/dto/request/FavoriteCertificatedType.java
  src/main/java/com/moa/moabackend/member/api/dto/response/MyFundingHistoryResDto.java
  src/main/java/com/moa/moabackend/member/api/dto/response/MyPundingHistoryResDto.java
  src/main/java/com/moa/moabackend/member/application/MemberService.java
  src/main/java/com/moa/moabackend/member/domain/Member.java
  src/main/java/com/moa/moabackend/member/domain/MemberType.java
  src/main/java/com/moa/moabackend/member/domain/repository/MemberRepository.java
  src/main/java/com/moa/moabackend/store/api/StoreController.java
  src/main/java/com/moa/moabackend/store/api/StoreControllerDocs.java
  src/main/java/com/moa/moabackend/store/api/dto/request/GetCurationDto.java
  src/main/java/com/moa/moabackend/store/application/StoreService.java
  src/main/java/com/moa/moabackend/store/domain/repository/StoreRepository.java
Labels: Docs, API, Feature, Refactor
